/**
 * Interview Practice Simulator — Minimal Fallback Question Bank
 *
 * Questions are generated by AI in real-time via Cloud Functions.
 * This file contains ONLY a small fallback bank (~15 generic questions)
 * used when AI is unavailable (network error, rate limit, etc.)
 *
 * Format: { id, q (question), f (framework hint), c (competency), d (difficulty 1-4) }
 */
    var QUESTION_BANK = {
      behavioral: {
        general: [
          { id:'fb_01', q:'Tell me about a time you had to learn something new quickly to complete a task.', f:'STAR: Describe what you needed to learn, the steps you took, and the outcome.', c:'adaptability', d:2 },
          { id:'fb_02', q:'Describe a situation where you worked as part of a team to achieve a challenging goal.', f:'STAR: Set the scene, your specific role, what you contributed, and the team result.', c:'teamwork', d:2 },
          { id:'fb_03', q:'Tell me about a time you had to deal with a difficult coworker or stakeholder.', f:'STAR: Focus on the conflict, how you handled it professionally, and what was resolved.', c:'conflict-resolution', d:2 },
          { id:'fb_04', q:'Give an example of when you took initiative without being asked.', f:'STAR: What did you notice, why did you act, what did you do, and what was the impact?', c:'initiative', d:2 },
          { id:'fb_05', q:'Describe a time when you failed or made a significant mistake. How did you handle it?', f:'STAR: Be honest about the failure, focus on what you learned and how you improved.', c:'adaptability', d:3 }
        ]
      },
      technical: {
        general: [
          { id:'fb_06', q:'Walk me through how you would approach solving a complex problem you have never seen before.', f:'Structure: clarify the problem, break it down, consider trade-offs, propose a solution, validate.', c:'problem-solving', d:2 },
          { id:'fb_07', q:'How do you stay current with developments in your field?', f:'Mention specific resources, communities, courses, and how you apply new learnings.', c:'initiative', d:1 },
          { id:'fb_08', q:'Describe a technical decision you made that had significant impact.', f:'STAR: What was the decision, what alternatives did you consider, why did you choose this path, what was the result?', c:'analytical', d:3 }
        ]
      },
      situational: {
        general: [
          { id:'fb_09', q:'What would you do if you were given a project with unclear requirements and a tight deadline?', f:'Show structured thinking: clarify scope, prioritize, communicate, deliver incrementally.', c:'problem-solving', d:2 },
          { id:'fb_10', q:'How would you handle a situation where you disagree with your manager\'s decision?', f:'Show professionalism: understand their perspective, present data-backed alternatives, accept the final call.', c:'communication', d:2 }
        ]
      },
      caseStudy: {
        general: [
          { id:'fb_11', q:'A company\'s revenue has declined 20% over the past year. Walk me through how you would diagnose the issue.', f:'Framework: segment the revenue (products, regions, customers), identify which declined, analyze root causes, propose solutions.', c:'analytical', d:3 }
        ]
      },
      panel: {
        general: [
          { id:'fb_12', q:'Tell us about a project that demonstrates your ability to work across different teams and stakeholders.', f:'STAR: Emphasize cross-functional collaboration, different perspectives managed, and unified outcome.', c:'leadership', d:3 }
        ]
      },
      phoneScreen: {
        general: [
          { id:'fb_13', q:'Tell me about yourself and why you are interested in this role.', f:'Structure: background (30s), current role (30s), why this company/role (30s). Keep under 2 minutes.', c:'communication', d:1 },
          { id:'fb_14', q:'What are your salary expectations for this role?', f:'Research market rates first. Give a range, anchor high, express flexibility based on total compensation.', c:'communication', d:2 }
        ]
      },
      finalRound: {
        general: [
          { id:'fb_15', q:'Where do you see yourself in five years, and how does this role fit into that vision?', f:'Show ambition aligned with the company. Connect your growth goals to what they need.', c:'communication', d:2 }
        ]
      }
    };
